name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Frontend
        run: |
          cd mcp_all_files/home/ubuntu/mcp_all_files/ebook-store
          pnpm install
          pnpm run build
          
          # Ensure proper SPA routing
          cd dist
          cp index.html 404.html
          
          # Create a public directory if it doesn't exist
          mkdir -p public
          
          # Copy static assets
          cp -r ../public/* . || true
          
          # Ensure .nojekyll exists
          touch .nojekyll

      - name: Build Admin Dashboard
        run: |
          cd mcp_all_files/home/ubuntu/mcp_all_files/ebook-admin-dashboard
          pnpm install
          pnpm run build
          
          # Create admin directory in frontend dist
          mkdir -p ../ebook-store/dist/admin
          cp -r dist/* ../ebook-store/dist/admin/
          
          # Setup admin SPA routing
          cd ../ebook-store/dist/admin
          cp index.html 404.html

      - name: Configure site
        run: |
          cd mcp_all_files/home/ubuntu/mcp_all_files/ebook-store/dist
          
          # Create SPA configuration
          cat > _app-config.js << 'EOL'
          window.APP_CONFIG = {
            baseUrl: "/ebookzone.in",
            basename: "/ebookzone.in",
            assetPath: "/ebookzone.in/assets",
            apiUrl: "/api"
          };
          EOL
          
          # Add script to index.html and 404.html
          for file in index.html 404.html admin/index.html admin/404.html; do
            if [ -f "$file" ]; then
              sed -i 's/<head>/<head><script src="\/_app-config.js"><\/script>/' "$file"
            fi
          done
          
          # Create security and routing headers
          cat > _headers << 'EOL'
          /*
            Cache-Control: public, max-age=31536000
            X-Frame-Options: DENY
            X-Content-Type-Options: nosniff
            X-XSS-Protection: 1; mode=block
            Referrer-Policy: strict-origin-when-cross-origin
          EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: mcp_all_files/home/ubuntu/mcp_all_files/ebook-store/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
