name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Build Frontend
      - name: Build Frontend
        working-directory: mcp_all_files/home/ubuntu/mcp_all_files/ebook-store
        run: |
          pnpm install
          pnpm run build
          touch dist/.nojekyll
          cp -r public/* dist/ 2>/dev/null || true

      # Build Admin Dashboard
      - name: Build Admin Dashboard
        working-directory: mcp_all_files/home/ubuntu/mcp_all_files/ebook-admin-dashboard
        run: |
          pnpm install
          pnpm run build
          mkdir -p ../ebook-store/dist/admin
          cp -r dist/* ../ebook-store/dist/admin/

      # Configure site for GitHub Pages
      - name: Configure site
        working-directory: mcp_all_files/home/ubuntu/mcp_all_files/ebook-store/dist
        run: |
          # Setup SPA routing
          cp index.html 404.html
          mkdir -p admin
          cp index.html admin/index.html
          cp index.html admin/404.html
          
          # Create base configuration
          cat > config.json << 'EOLCONF'
          {
            "baseUrl": "/ebookzone.in",
            "apiUrl": "/api",
            "assetsPath": "./assets"
          }
          EOLCONF

          # Set security headers
          cat > _headers << 'EOLHEAD'
          /*
            Cache-Control: public, max-age=31536000
            X-Frame-Options: DENY
            X-Content-Type-Options: nosniff
            X-XSS-Protection: 1; mode=block
            Referrer-Policy: strict-origin-when-cross-origin
            Permissions-Policy: camera=(), microphone=(), geolocation=()
          EOLHEAD

      # Upload built files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: mcp_all_files/home/ubuntu/mcp_all_files/ebook-store/dist

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
